# Generated by Django 3.2 on 2023-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupArrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20, verbose_name='연령대')),
                ('num_age_arrested', models.IntegerField(verbose_name='검거 수 (단위 : 명)')),
            ],
            options={
                'verbose_name_plural': '대시보드 2 : 2022년 기준 연령대별 단속 내역',
            },
        ),
        migrations.CreateModel(
            name='DrugItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_items', models.CharField(max_length=20, verbose_name='마약 품목')),
                ('drug_items_arrested', models.IntegerField(verbose_name='압수량 (단위 : g)')),
            ],
            options={
                'verbose_name_plural': '대시보드 3 : 2022년 기준 마약류 품목별 단속 현황',
            },
        ),
        migrations.CreateModel(
            name='ForeignDrugUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_Foreign_drug_users', models.IntegerField(verbose_name='연도')),
                ('personnel', models.IntegerField(verbose_name='외국인 마약사범 수 (단위 : 명)')),
                ('f_num_drug_user', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='국내외 전체사범 중 비율 (%)')),
            ],
            options={
                'verbose_name_plural': '대시보드 5 : 최근 5년간 국내 외국인 마약류 사범 현황',
            },
        ),
        migrations.CreateModel(
            name='ForeignDrugUserNation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='국적')),
                ('num_drug_user', models.IntegerField(verbose_name='사범 수 (단위 : 명)')),
                ('percent', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='국적별 비중 (%)')),
            ],
            options={
                'verbose_name_plural': '대시보드 6 : 2022년 기준 국내 외국인 마약사범 국적별 현황',
            },
        ),
        migrations.CreateModel(
            name='GlobalAddicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='지역')),
                ('num_drug_addicts', models.IntegerField(verbose_name='중독자 수 (단위 : 만 명)')),
            ],
            options={
                'verbose_name_plural': '대시보드 4 : 전 세계 지역별 마약 중독자 수',
            },
        ),
        migrations.CreateModel(
            name='NumDrugUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_drug_user', models.IntegerField(verbose_name='연도')),
                ('num_drug_user', models.IntegerField(verbose_name='마약사범 수 (단위 : 명)')),
            ],
            options={
                'verbose_name_plural': '대시보드 1 : 최근 5년간 마약류 사범 수',
            },
        ),
        migrations.CreateModel(
            name='RehabData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_rehab_data', models.IntegerField(verbose_name='연도')),
                ('cure_protect', models.IntegerField(verbose_name='치료보호 (단위 : 명)')),
                ('cure_custody', models.IntegerField(verbose_name='치료감호 (단위 : 명)')),
            ],
            options={
                'verbose_name_plural': '대시보드 8 : 2021년 까지 중독자 치료보호 및 감호 현황',
            },
        ),
        migrations.CreateModel(
            name='RepeatCrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_repeat_crime', models.IntegerField(verbose_name='연도')),
                ('all_drug_user', models.IntegerField(verbose_name='전체사범 수 (단위 : 명)')),
                ('rp_drug_user', models.IntegerField(verbose_name='재범인원 수 (단위 : 명)')),
                ('percent', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='재범률 (%)')),
            ],
            options={
                'verbose_name_plural': '대시보드 7 : 2021년 까지 연도별 재범률',
            },
        ),
    ]
